/* Haplo Platform                                     http://haplo.org
 * (c) Haplo Services Ltd 2006 - 2016    http://www.haplo-services.com
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.         */

/*
 * AUTOMATICALLY GENERATED FILE - DO NOT EDIT
 *
 * Run
 *   script/runner lib/tasks/update_js_runtime_constants.rb
 * to rebuild.
 */
_.extend(O,{
  T_BLOB:6,
  T_BOOLEAN:5,
  T_DATETIME:4,
  T_IDENTIFIER_CONFIGURATION_NAME:40,
  T_IDENTIFIER_EMAIL_ADDRESS:29,
  T_IDENTIFIER_FILE:27,
  T_IDENTIFIER_ISBN:28,
  T_IDENTIFIER_POSTAL_ADDRESS:36,
  T_IDENTIFIER_POSTCODE:31,
  T_IDENTIFIER_TELEPHONE_NUMBER:32,
  T_IDENTIFIER_URL:30,
  T_INTEGER:2,
  T_NUMBER:3,
  T_OBJREF:0,
  T_TEXT:16,
  T_TEXT_DOCUMENT:25,
  T_TEXT_MULTILINE:33,
  T_TEXT_PARAGRAPH:24,
  T_TEXT_PERSON_NAME:35,
  T_TEXT_PLUGIN_DEFINED:64,
  T_TEXT__APP_MIN:24,
  T_TEXT__MIN:16,
  T_TYPEREF:1,
  T_REF:0
});
_.extend(O,{
  PERM_READ:1,
  PERM_CREATE:2,
  PERM_UPDATE:4,
  PERM_RELABEL:8,
  PERM_DELETE:16,
  PERM_APPROVE:32,
  PERM_ALL:63,
  STATEMENT_ALLOW:1,
  STATEMENT_DENY:0,
  STATEMENT_RESET:2,
});
_.extend(O,{
  PRECISION_CENTURY: 'C',
  PRECISION_DECADE: 'D',
  PRECISION_YEAR: 'Y',
  PRECISION_MONTH: 'M',
  PRECISION_DAY: 'd',
  PRECISION_HOUR: 'h',
  PRECISION_MINUTE: 'm',
  '$ALL_PRECISIONS':{"C":true,"D":true,"Y":true,"M":true,"d":true,"h":true,"m":true}
});
var HTTP = {
  CONTINUE: 100,
  SWITCHING_PROTOCOLS: 101,
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,
  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  USE_PROXY: 305,
  // 306 is unused
  TEMPORARY_REDIRECT: 307,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  REQUEST_ENTITY_TOO_LARGE: 413,
  REQUEST_URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  REQUESTED_RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505
};
