#!/bin/sh

# (c) Haplo Services Ltd 2006 - 2016    http://www.haplo-services.com
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

. config/paths-`uname`.sh

#public version, fixed arguments
$JRUBY_HOME/bin/jruby deploy/_release.rb "$@" --no-clean-up --input-dir=. latest
deploy/fix-classpath /tmp/haplo-build /opt/haplo
mkdir -p /tmp/haplo-build/etc/properties
# preserve any existing properties
if [ -f /opt/haplo/etc/properties/email_delivery_enabled ]; then
    cp /opt/haplo/etc/properties/email_delivery_enabled /tmp/haplo-build/etc/properties/email_delivery_enabled
else
    echo "no" > /tmp/haplo-build/etc/properties/email_delivery_enabled
fi
if [ -f /opt/haplo/etc/properties/plugin_debugging_support ]; then
    cp /opt/haplo/etc/properties/plugin_debugging_support /tmp/haplo-build/etc/properties/plugin_debugging_support
else
    echo "no" > /tmp/haplo-build/etc/properties/plugin_debugging_support
fi
if [ -f /opt/haplo/etc/properties/register_mdns_hostnames ]; then
    cp /opt/haplo/etc/properties/register_mdns_hostnames /tmp/haplo-build/etc/properties/register_mdns_hostnames
else
    echo "no" > /tmp/haplo-build/etc/properties/register_mdns_hostnames
fi
# need to copy jruby to deployment
mkdir -p /tmp/haplo-build/vendor
cd $JRUBY_HOME/..
tar cf - jruby | ( cd /tmp/haplo-build/vendor ; tar xf -)
# and copy maxmind
mkdir -p /tmp/haplo-build/information
cd $KINFORMATION_HOME
tar cf - maxmind-geolite2 | ( cd /tmp/haplo-build/information ; tar xf -)
# and we need a copy of cacert.pem in a known location
mkdir -p /tmp/haplo-build/ssl
if [ -f /etc/ssl/cacert.pem ]; then
    cp /etc/ssl/cacert.pem /tmp/haplo-build/ssl
else
    cat /etc/ssl/certs/*.pem > /tmp/haplo-build/ssl/cacert.pem
fi
cd /tmp/haplo-build
#
# we want to make the deployable image, and thus the docker image,
# no larger than they need to be
#
# don't deploy the git metadata
rm -fr .git
rm -f .gitignore
# tidy up bits of jruby we'll never use
rm -f vendor/jruby/bin/*.exe
rm -f vendor/jruby/bin/*.dll
rm -fr vendor/jruby/tool
rm -fr vendor/jruby/samples
rm -f vendor/jruby/bin/*.bat
rm -fr vendor/jruby/lib/jni/*Windows
rm -fr vendor/jruby/lib/jni/ppc*
rm -fr vendor/jruby/docs/man
rm -f vendor/jruby/docs/pom.xml
# remove duplication
if [ -f jars/jruby.jar -a -f vendor/jruby/lib/jruby.jar ]; then
    rm -f jars/jruby.jar
    ln vendor/jruby/lib/jruby.jar jars/jruby.jar
fi
# create deployable tarball
tar cf /tmp/haplo-build.tar .
cd /tmp
rm -fr haplo-build
echo "Archive built, unpack /tmp/haplo-build.tar in /opt/haplo to deploy"
