#!/bin/sh

# Haplo Platform                                     http://haplo.org
# (c) ONEIS Ltd 2006 - 2015                    http://www.oneis.co.uk
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


# Tests the application after the deployment processing

# When debugging tests, check out source elsewhere, then use something like
#   deploy/release --for-testing --no-clean-up --input /export/home/ben/t-oneis version
# and comment out script/test onwards below.

if [ ! -f target/classpath.txt ]; then
    echo "ERROR: have you built haplo?"
    echo "run ./fetch-and-compile.sh first"
    exit 1
fi

deploy/release --for-testing

if [ ! -f /tmp/haplo-build.tar ]; then
    "ERROR: deployment release generation failed, exiting."
    exit 1
fi

mkdir -p code
chmod 0755 code
cd code
tar xf /tmp/haplo-build.tar
rm -f /tmp/haplo-build.tar
mkdir -p log
cp static/stylesheets/a.css static/stylesheets/app.css
script/test
cd ..
rm -rf code
