#!/bin/sh

# Haplo Platform                                     http://haplo.org
# (c) ONEIS Ltd 2006 - 2015                    http://www.oneis.co.uk
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


# Usage: script/doc-tool [action]
# Actions:
#  server - runs the test document server (default)
#  check - checks all the pages will render correctly
#  publish - write files for uploading to the web server

. config/paths-`uname`.sh

$JRUBY_HOME/bin/jruby doc/scripts/doctool.rb $@
