#!/bin/sh

# Haplo Platform                                     http://haplo.org
# (c) Haplo Services Ltd 2006 - 2016    http://www.haplo-services.com
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


# Usage:
#   script/javascript-tester
#     Wait for changes to files, check new files as they're edited
#   script/javascript-tester all
#     Check all the JavaScript files
#   script/javascript-tester <filename>
#     Check a single JavaScript file

. config/paths-`uname`.sh

$JRUBY_HOME/bin/jruby test/lib/javascript_tester.rb $@
