#!/bin/sh

# Haplo Platform                                     http://haplo.org
# (c) Haplo Services Ltd 2006 - 2016    http://www.haplo-services.com
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

set -e

. config/paths-`uname`.sh

if [ X$KFRAMEWORK_ENV = X ]
then
    KFRAMEWORK_ENV=development
    export KFRAMEWORK_ENV
fi
if [ X$KFRAMEWORK_BITS = X ]
then
    KFRAMEWORK_BITS=64
fi

# Make sure a plugin debugging choice is set -- allows it to be changed without accidently getting committed, and defaults to yes
if [ X$KFRAMEWORK_ENV = Xdevelopment ]
then
	if [ ! -f tmp/properties/plugin_debugging_support ]
	then
		echo yes > tmp/properties/plugin_debugging_support
	fi
fi


framework/haplo utility $KFRAMEWORK_BITS config/java.config $JAVA_EXECUTABLE `pwd` $KFRAMEWORK_ENV $@

