#!/bin/sh

# Haplo Platform                                     http://haplo.org
# (c) Haplo Services Ltd 2006 - 2016    http://www.haplo-services.com
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

set -e

. config/paths-`uname`.sh

if [ X$KFRAMEWORK_ENV = X ]
then
    KFRAMEWORK_ENV=development
    export KFRAMEWORK_ENV
fi

if [ X$KFRAMEWORK_ENV = Xdevelopment ]
then
	# Make sure a plugin debugging choice is set -- allows it to be set without accidently getting committed, and defaults to no
	if [ ! -f tmp/properties/plugin_debugging_support ]
	then
		echo yes > tmp/properties/plugin_debugging_support
	fi
	# Default server classification tags in development
	if [ ! -f tmp/properties/server_classification_tags ]
	then
		echo platform-development-environment > tmp/properties/server_classification_tags
	fi
fi


framework/haplo utility config/java.config $JAVA_EXECUTABLE `pwd` $KFRAMEWORK_ENV $@

